main: xyz.globecraft.addons.AddonsPlugin
author: Antti & Kalpo
name: GlobecraftAddons
version: 1.0.0
api-version: 1.15
depend: [WorldEdit, WorldGuard]
commands:
  gcaddons:
    permission: gcaddons.list
    description: Shows all of the available addons or the help of a single addon.
    usage: '/<command> [addon]'
    aliases: [gcaddon]
  gcreload:
    permission: gcaddons.reload
    description: Reload a Globecraft addon
    usage: '/<command> [addon]'
  gcdisable:
    permission: gcaddons.toggle
    description: Disable a Globecraft addon
    usage: '/<command> [addon]'
  gcenable:
    permission: gcaddons.toggle
    description: Enable a Globecraft addon
    usage: '/<command> [addon]'
  rtp:
    permission: gcaddons.rtp
    description: Randomly teleport somewhere on the map
    usage: '/<command>'
    aliases: [randomtp]
  vday:
    permission: gcaddons.voteskipnight
    description: Vote to skip the night
    usage: '/<command>'
    aliases: [vd, voteday, dset, dvote]
